### PR TITLE
Submit url and urls

### PR DESCRIPTION
**Pull request by damianmarti**
Contribute page to submit a URL or URLs:

localhost_3000_contribute (3)

If there are any errors when submitting the URLs it will show the submitted link details showing which links were successfully submitted and which have an error.

localhost_3000_contribute (2)

### CODE REVIEW

**Comment by amy-jung** [comment]
looks good to me!

**Comment by carletex** [comment]
Thanks for this @damianmarti 

Will be testing & merging this tomorrow.

Questions: Do we want to disable the submission until #43 is implemented? Or should we leave it open?

I plan to have a basic signing (without the attestation stuff, that we can add later) later this week, so I guess it's not a big deal if we start getting submissions :D

**Comment by damianmarti** [comment]
> Thanks for this @damianmarti
> 
> Will be testing & merging this tomorrow.
> 
> Questions: Do we want to disable the submission until #43 is implemented? Or should we leave it open?
> 
> I plan to have a basic signing (without the attestation stuff, that we can add later) later this week, so I guess it's not a big deal if we start getting submissions :D

I don't think that the site is linked from too many places to be able to be spammed by bots (but maybe I'm wrong), so I think we can deploy it even before we add the signing feature.

**Comment by carletex** [comment]
> I don't think that the site is linked from too many places to be able to be spammed by bots (but maybe I'm wrong), so I think we can deploy it even before we add the signing feature.

Agree!

---

This is working great @damianmarti!! Thank you <3

Just changed the table name to «Submission» and fixed some prettier stuff (maybe you haven't enabled it for this project)

Also:
- Run the migration on the production database
- Updated the env var name in Vercel (NEXT_PUBLIC_...).

Merging this, thanks!

**Comment by damianmarti** [comment]
> > I don't think that the site is linked from too many places to be able to be spammed by bots (but maybe I'm wrong), so I think we can deploy it even before we add the signing feature.
> 
> Agree!
> 
> This is working great @damianmarti!! Thank you <3
> 
> Just changed the table name to «Submission» and fixed some prettier stuff (maybe you haven't enabled it for this project)
> 
> Also:
> 
> * Run the migration on the production database
> * Updated the env var name in Vercel (NEXT_PUBLIC_...).
> 
> Merging this, thanks!

Thanks!!

Yes, sorry, I think I forgot to enabled the pretier for the project!

**Pull request merged**
