### PR TITLE
Add advanced search

### PR DESCRIPTION
**Pull request by damianmarti**
Added search features to the backend:
- Search by multiple organizations
- Search by multiple categories
- Filter by dates
- Sort by title

Added backend endpoints to get categories and organizations.

Added advanced search to the frontend:
- Search by multiple organizations
- Search by multiple categories
- Filter by dates
- Sort by ranking, title, author, most recent

The advanced search form looks ugly, it needs to be styled.

### CODE REVIEW

**Comment by carletex** [comment]
Thanks for this @damianmarti !! Looking great!

I've been testing and I found one issue with `organizations`: when I manually set the organizations to filter + click search, it doesn't work (it returns all the records). See screenshot (URL query not right, it's empty). I see that `setOrganizations` is not used, so that might be it?

image

**Comment by carletex** [comment]
> The advanced search form looks ugly, it needs to be styled.

I'll work on this BTW ;)

**Comment by damianmarti** [comment]
> Thanks for this @damianmarti !! Looking great!
> 
> I've been testing and I found one issue with `organizations`: when I manually set the organizations to filter + click search, it doesn't work (it returns all the records). See screenshot (URL query not right, it's empty). I see that `setOrganizations` is not used, so that might be it?
> 
> image

I did a refactor before pushing the code, maybe I introduce a bug there. I will check it!

**Comment by damianmarti** [comment]
> > Thanks for this @damianmarti !! Looking great!
> > I've been testing and I found one issue with `organizations`: when I manually set the organizations to filter + click search, it doesn't work (it returns all the records). See screenshot (URL query not right, it's empty). I see that `setOrganizations` is not used, so that might be it?
> > image
> 
> I did a refactor before pushing the code, maybe I introduce a bug there. I will check it!

@carletex what do you mean by "manually set the organizations to filter"? Thanks!

**Comment by carletex** [comment]
@damianmarti 

1.Went to the search page, 
2. select gitcoin & aave in the organzations field
3. click search
4. The page loads and the results are empty (the URL didn't change)


Doing the same with "dates" work!

**Comment by carletex** [comment]
Thanks @damianmarti, seems to be working great now!!

Even if we don't have the styles for it, let's merge so we can test live... and I'll do the styling tweaks in another PR

**Pull request merged**
